---
prefer_indep_over_os_packages: false
osdeps_mode: all
reused_autoproj_installations: []
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
typelib_cxx_loader: castxml
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
apt_dpkg_update: true
USE_PYTHON: true
syskit_use_bundles: true
separate_prefixes: true
python_executable: "/usr/bin/python3"
